
model = "gpt-6-astra"
model_reasoning_effort = "high"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."unified-computer-use@openai-bundled"]
enabled = false

[plugins."computer-use@openai-bundled"]
enabled = false

[plugins."code-review@openai-bundled"]
enabled = true

[features]
hooks = true
js_repl = false

[desktop]
conversationDetailMode = "STEPS_PROSE"
ambient-suggestions-enabled = false
mac-menu-bar-enabled = false
followUpQueueMode = "queue"
dock-icon-preference = "codex-system"
